image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - dist/

pages:
  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      - dist
  only:
    - master
