export const milestones = [
  {
    id: 1,
    img: '/img/about-us/about-gojek-2010.svg',
    class: '',
    bgClass: 'about-green-bg',
    bgPattern: 'about-pattern-a',
    title: 'In 2010',
    description:
      "Gojek started with a mission to improve the livelihoods of local ojeks (motorcycle taxis). Every customer was 'matched' manually with a driver via a call center.",
    linkText: '',
    linkURL: '',
  },
  {
    id: 2,
    img: '/img/about-us/about-gojek-2015.svg',
    class: '',
    bgClass: 'about-blue-bg',
    bgPattern: 'about-pattern-b',
    title: 'In 2015',
    description:
      'A version of the app was launched to automate matchmaking between customers and driver partners. <br/>Orders scaled from 3,000 to 100,000 a day.',
    linkText: '',
    linkURL: '',
  },
  {
    id: 3,
    img: '/img/about-us/about-gojek-end-of-2015.svg',
    class: '',
    bgClass: 'about-purple-bg',
    bgPattern: 'about-pattern-c',
    title: 'End of 2015',
    description:
      'Systems were crashing because of a major spike in volumes. <br/> We rewrote a key piece of technology in Golang in under 3 days.',
    linkText: 'Read our story',
    linkURL: `${process.env.domain}blog/how-gojek-manages-1-million-drivers-with-12-engineers-part-1-2`,
  },
  {
    id: 4,
    img: '/img/about-us/about-gojek-2016.svg',
    class: 'text-green-light',
    bgClass: 'about-green-bg',
    bgPattern: 'about-pattern-a',
    title: 'In 2016',
    description:
      'Orders climbed to 300,000+ a day. Driver incomes increased by 150%. In April, with the launch of GoPay, cashless transactions were introduced. 18 million monthly bookings. 🤯',
    linkText: '',
    linkURL: '',
  },
  {
    id: 5,
    img: '/img/about-us/about-gojek-the-big-rewrite.svg',
    class: 'text-green-light',
    bgClass: 'about-orange-bg',
    bgPattern: 'about-pattern-b',
    title: 'The big rewrite',
    description:
      'Downtimes were a routine affair and leaky faucets needed to be fixed. <br class="d-none d-md-block"/> "No project has a budget and impact as big as this in Gojek\'s history"<br/> - From Nadiem’s internal mail.',
    linkText: 'Read our story',
    linkURL: `${process.env.domain}blog/how-gojek-manages-1-million-drivers-with-12-engineers-part-2-2`,
  },
  {
    id: 6,
    img: '/img/about-us/about-gojek-2017.svg',
    class: 'text-green-light',
    bgClass: 'about-green-bg',
    bgPattern: 'about-pattern-c',
    title: 'In 2017',
    description:
      'Reached 30 million monthly bookings. Gojek employed more than 30,000 people with disabilities.',
    linkText: 'Watch the video',
    linkURL: 'https://www.youtube.com/watch?v=tu-5s8KhzvQ&feature=youtu.be',
  },
  {
    id: 7,
    img: '/img/about-us/about-gojek-2018.svg',
    class: 'text-green-light',
    bgClass: 'about-blue-bg',
    bgPattern: 'about-pattern-a',
    title: 'By 2018',
    description:
      'Gojek did 100+ million orders across 18+ products. Total order volume growth: 1100x.',
    linkText: '',
    linkURL: '',
  },
  {
    id: 8,
    img: '/img/about-us/about-gojek-going-international.svg',
    class: 'text-green-light',
    bgClass: 'about-pink-bg',
    bgPattern: 'about-pattern-b',
    title: 'Going international',
    description: 'Gojek went live in Vietnam 🇻🇳, Singapore 🇸🇬, and Thailand 🇹🇭 in 2018.',
    linkText: 'Read the story',
    linkURL: 'http://bit.ly/2XTN6WK',
  },
  {
    id: 9,
    img: '/img/about-us/about-gojek-2019.svg',
    class: 'text-green-light',
    bgClass: 'about-green-bg',
    bgPattern: 'about-pattern-c',
    title: 'In 2019',
    description:
      "Gojek became Indonesia's first decacorn. We also underwent a massive rebranding and had a new identity: Solv.",
    linkText: 'Read about Solv',
    linkURL: 'http://bit.ly/2Sw2tmK',
  },
  {
    id: 10,
    img: '/img/about-us/about-gojek-uplifting-the-economy.svg',
    class: 'text-green-light',
    bgClass: 'about-orange-bg',
    bgPattern: 'about-pattern-a',
    title: 'Uplifting the economy',
    description:
      "Gojek contributed $7.1 billion to the Indonesian economy in 2019 (that's more than twice of 2018!)",
    linkText: '',
    linkURL: '',
  },
];
