export const departments = [
  {
    name: 'Transport',
    class: 'text-green',
    bgClass: 'transport',
    borderColor: '#008c15',
    logos: [
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
    ],
  },
  {
    name: 'Payments',
    class: 'text-blue',
    bgClass: 'payments',
    borderColor: '#00aed6',
    logos: [
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
    ],
  },
  {
    name: 'Food Delivery',
    class: 'text-orange-light',
    bgClass: 'food-delivery',
    borderColor: '#ff7f32',
    logos: [
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
    ],
  },
  {
    name: 'Logistics',
    class: 'text-red',
    bgClass: 'logistics',
    borderColor: '#ee2737',
    logos: [
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
    ],
  },
  {
    name: 'Entertainment',
    class: 'text-pink-light',
    bgClass: 'entertainment',
    borderColor: '#df1995',
    logos: [
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
    ],
  },
  {
    name: 'Lifestyle Service',
    class: 'text-yellow-light',
    bgClass: 'lifestyle-service',
    borderColor: '#f7ce55',
    logos: [
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
      '/img/logo-horizontal.svg',
    ],
  },
];

export const goal = {
  title: 'Our goal',
  description:
    'We’re dedicated to creating (and scaling) positive socio-economic impact for our ecosystem of users. An ecosystem where our 2 million+ driver-partners, 500,000+ merchant partners, as well as 50,000+ service providers, are all first party citizens.',
  data: [
    {
      id: 1,
      title: '2 Million+',
      subtitle: 'Driver partners',
      img: './img/placeholder.png',
      color: '#00aa13',
      front: 'showFirstFrontimage',
      back: 'showFirstBackimage',
    },
    {
      id: 2,
      title: '500,000+',
      subtitle: 'Merchant partners',
      img: './img/placeholder.png',
      color: '#0294b3',
      front: 'showSecondFrontimage',
      back: 'showSecondBackimage',
    },
    {
      id: 3,
      title: '50,000+',
      subtitle: 'Service providers',
      img: './img/placeholder.png',
      color: '#df1995',
      front: 'showThirdFrontimage',
      back: 'showThirdBackimage',
    },
  ],
};
