export const perks = [
  {
    id: 1,
    title: 'We talk about mental health',
    description: 'Free counselling for employees & families.',
    bgColor: '#df1995',
    height: '426px',
    show: '1',
  },
  {
    id: 2,
    title: 'We help you stay connected',
    description: 'Mobile and internet bill reimbursement.',
    bgColor: '#fcaa00',
    height: '280px',
    show: '1',
  },
  {
    id: 7,
    title: 'Refer & earn',
    description: 'Meet friends for lunch, every other day.',
    bgColor: '#00aed6',
    img: '../img/life-at-gojek/perks/refer-and-earn.svg',
    height: '426px',
    show: '2',
  },
  {
    id: 8,
    title: 'Health insurance',
    description: 'Life, surgery, dental, inpatient, outpatient and more.',
    bgColor: '#00aa13',
    height: '280px',
    show: '2',
  },
  {
    id: 3,
    title: 'Corporate loans',
    description: 'Big goals? Allow us to lend a hand.',
    bgColor: '#93328e',
    height: '280px',
    show: '1',
  },
  {
    id: 4,
    title: 'Voracious reader?',
    description: 'Let us pick up the tab for  books.',
    bgColor: '#00aa13',
    img: '../img/life-at-gojek/perks/voracious-reader.svg',
    height: '426px',
    show: '1',
  },
  {
    id: 9,
    title: 'Unity in diversity',
    description: 'Work with superstars from across 31 nationalities.',
    bgColor: '#f4364c',
    height: '280px',
    show: '2',
  },
  {
    id: 10,
    title: 'Community learning',
    description: 'Industry-wide meetups, events and conferences. We pay. You learn.',
    bgColor: '#ff7f32',
    img: '',
    height: '426px',
    show: '2',
  },
  {
    id: 5,
    title: 'Learning & development',
    description: 'Free courses on Coursera, and in-house mentorship.',
    bgColor: '#ff7f32',
    img: '../img/life-at-gojek/perks/learning-and-development.svg',
    height: '426px',
    show: '1',
  },
  {
    id: 6,
    title: 'Your health matters',
    description: 'Health and fitness related expenditure is on us',
    bgColor: '#00aed6',
    height: '280px',
    show: '1',
  },
  {
    id: 11,
    title: 'Fly for work & fun',
    description: 'Explore new offices, different cultures, and a thousand islands!',
    bgColor: '#93328e',
    img: '',
    height: '426px',
    show: '2',
  },
  {
    id: 12,
    title: '200-seater amphitheatre',
    description: 'For meetups, movies and madness.',
    bgColor: '#df1995',
    height: '280px',
    show: '2',
  },
];
export const mobilePerks = [
  {
    id: 1,
    title: 'Your work, your time',
    description: "We don’t ask when/whether you're coming or going.",
    bgColor: '#93328e',
    img: '../img/life-at-gojek/perks/your-work-your-time.svg',
    height: '430px',
    show: '1',
  },
  {
    id: 6,
    title: 'We talk about mental health',
    description: 'Free counselling for employees & families.',
    bgColor: '#00aed6',
    height: '280px',
    show: '1',
  },
  {
    id: 3,
    title: 'Voracious reader?',
    description: 'Let us pick up the tab for  books.',
    bgColor: '#df1995',
    img: '',
    height: '426px',
    show: '1',
  },
  {
    id: 7,
    title: 'Refer & earn',
    description: 'Meet friends for lunch, every other day.',
    bgColor: '#00aed6',
    img: '../img/life-at-gojek/perks/refer-and-earn.svg',
    height: '426px',
    show: '2',
  },
  {
    id: 10,
    title: 'The Gojek Cup',
    description: 'Our annual sports event is no child’s play.',
    bgColor: '#fcaa00',
    height: '280px',
    show: '2',
  },
  {
    id: 9,
    title: 'Unity in diversity',
    description: 'Work with superstars from across 31 nationalities.',
    bgColor: '#f4364c',
    height: '280px',
    show: '2',
  },
  {
    id: 13,
    title: 'Health insurance',
    description: 'Life, surgery, dental, inpatient, outpatient and more.',
    bgColor: '#f06400',
    height: '280px',
    show: '3',
  },
  {
    id: 15,
    title: 'GoPay credits',
    description: 'Coz our growth is credited to you.',
    bgColor: '#00aed6',
    img: '../img/life-at-gojek/perks/gopay-credits.svg',
    height: '426px',
    show: '3',
  },
  {
    id: 18,
    title: 'Clubs for all',
    description: 'Football, Badminton, Boxing Yoga, Zumba, and more.',
    bgColor: '#00aa13',
    img: '../img/life-at-gojek/perks/clubs-for-all.svg',
    height: '514px',
    show: '3',
  },
  {
    id: 20,
    title: 'Sleeping room',
    description: 'When in doubt, take a nap. Late hours? Stay over.',
    bgColor: '#f06400',
    height: '280px',
    show: '3',
  },
  {
    id: 2,
    title: 'Fly for work & fun',
    description: 'Explore new offices, different cultures, and a thousand islands!',
    bgColor: '#ff7f32',
    height: '282px',
    show: '1',
  },
  {
    id: 4,
    title: 'We help you stay connected',
    description: 'Mobile and internet bill reimbursement.',
    bgColor: '#fcaa00',
    height: '280px',
    show: '1',
  },
  {
    id: 5,
    title: 'Your health matters',
    description: 'Health and fitness related expenditure is on us',
    bgColor: '#93328e',
    img: '../img/life-at-gojek/perks/health-benifits.svg',
    height: '426px',
    show: '1',
  },
  {
    id: 8,
    title: 'For moms-to-be',
    description: 'A 6-month maternity leave + WFH options. No questions asked.',
    bgColor: '#ff7f32',
    height: '280px',
    show: '2',
  },
  {
    id: 12,
    title: 'Community learning',
    description: 'Industry-wide meetups, events and conferences. We pay. You learn.',
    bgColor: '#df1995',
    img: '',
    height: '426px',
    show: '2',
  },
  {
    id: 11,
    title: 'Corporate loans',
    description: 'Big goals? Allow us to lend a hand.',
    bgColor: '#00aed6',
    img: '../img/life-at-gojek/perks/corporate-loans.svg',
    height: '426px',
    show: '2',
  },
  {
    id: 14,
    title: 'Learning & development',
    description: 'Free courses on Coursera, and in-house mentorship.',
    bgColor: '#00aa13',
    img: '../img/life-at-gojek/perks/learning-and-development.svg',
    height: '510px',
    show: '3',
  },
  {
    id: 16,
    title: '200-seater amphitheatre',
    description: 'For meetups, movies and madness.',
    bgColor: '#df1995',
    height: '280px',
  },
  {
    id: 19,
    title: 'Gamers’ got a life',
    description: 'We’ve got you playrooms with arcade games.',
    bgColor: '#f06400',
    height: '280px',
    show: '3',
  },
  {
    id: 17,
    title: 'CSR Initiatives',
    description: 'Subsidising GoCar rides for the elderly with dementia + more.',
    bgColor: '#df1995',
    img: '../img/life-at-gojek/perks/csr-activities.svg',
    height: '426px',
    show: '3',
  },
];

export const posts = [
  {
    id: 1,
    title: 'How GOJEK Manages 1 million Drivers With 12 Engineers',
    img: '../img/life-at-gojek/blog/managing-1-million-drivers.png',
    link: '/blog/how-gojek-manages-1-million-drivers-with-12-engineers-part-1',
  },
  {
    id: 2,
    title: 'Why We Swear by the RCA <br class="d-none d-md-block" /> <br /> <br  />',
    img: '../img/life-at-gojek/blog/why-we-swear-by-rca.png',
    link: '/blog/why-we-swear-by-the-rca',
  },
  {
    id: 3,
    title:
      'How Design Can Build or Break a Business<br class="d-none d-md-block" /> <br class="d-none d-md-block" />',
    img: '../img/life-at-gojek/blog/design-can-build-or-break-business.png',
    link: '/blog/how-design-can-build-or-break-a-business-1-of-3',
  },
  {
    id: 4,
    title: 'The Rise and Fall of Mod Apps <br class="d-block d-md-none" /> <br/>',
    img: '../img/life-at-gojek/blog/rise-and-fall-of-mod-apps.png',
    link: 'https://www.instagram.com/p/B_XQkmvAlmb/',
  },
  {
    id: 5,
    title: 'When Canned Messages Opened a Can of Worms <br class="d-none d-md-block"/>',
    img: '../img/life-at-gojek/blog/canned-messages.png',
    link: 'https://www.instagram.com/p/CApot3pg4p9/',
  },
  {
    id: 6,
    title: 'Don’t be Proud of being a Perfectionist <br class="d-none d-md-block"/>',
    img: '../img/life-at-gojek/blog/dont-be-proud-of-perfectionist.png',
    link: 'https://www.instagram.com/p/CBQIwpMgH-t/',
  },
];

export const socialImpact = {
  heading: 'Social Impact',
  description:
    'Gojek is a verb in Southeast Asia. We got here because of our commitment to improve the lives of millions of Southeast Asians. A glimpse of how we’ve impacted the communities around us:',
  data: [
    {
      id: 1,
      title: 'Gojek contributed a total of $7.1 billion to Indonesia’s economy in 2019.',
      image: '../img/life-at-gojek/social-impact/contribution-to-economy.svg',
      color: '#74d2e7',
    },
    {
      id: 2,
      title:
        'Since the start of the COVID-19 pandemic, Gojek has helped more than 120,000 MSMEs in Indonesia to go digital',
      image: '../img/life-at-gojek/social-impact/helping-msme.svg',
      color: '#e2acd7',
    },
    {
      id: 3,
      title:
        'The average Gojek driver partner’s income is more than Indonesia’s average minimum wage.',
      image: '../img/life-at-gojek/social-impact/drivers-income.svg',
      color: '#ffc27b',
    },
    {
      id: 4,
      title:
        'Gojek is ranked 11th of 52 companies that made it to the annual Fortune "Change the World" list in 2019, becoming the only company in Southeast Asia to make it to the list twice.',
      image: '../img/life-at-gojek/social-impact/changing-the-world.svg',
      color: '#a1d884',
    },
    {
      id: 5,
      title:
        'Since joining, the quality of life for driver partners has increased.  83% of GoRide & 91% of GoCar drivers can now send their children to school.',
      image: '../img/life-at-gojek/social-impact/quality-of-life.png',
      color: '#ffb1bb',
    },
    {
      id: 6,
      title:
        'Merchants who sign up for GoFood have reported order volumes increasing by as much as 345%.',
      image: '../img/life-at-gojek/social-impact/gojek-merchants.svg',
      color: '#eabedb',
    },
  ],
};

export const teams = [
  {
    name: 'Kernel',
    slug: 'kernel',
    bgColor: '#ff695b',
    bgImg: '/img/careers/kernel.png',
  },
  {
    name: 'The Identity & Communication Platform',
    slug: 'identity-and-communication-platform',
    bgColor: '#ffb31c',
    bgImg: '/img/careers/identity-and-communication.png',
  },
  {
    name: 'Operations Platform',
    slug: 'operations-platform',
    bgColor: '#772583',
    bgImg: '/img/careers/operations.png',
  },
  {
    name: 'Kernel',
    slug: 'kernel',
    bgColor: '#ff695b',
    bgImg: '/img/careers/kernel.png',
  },
  {
    name: 'Test',
    slug: 'identity-and-communication-platform',
    bgColor: '#ffb31c',
    bgImg: '/img/careers/identity-and-communication.png',
  },
];

export const teamsSliderSettings = {
  infinite: true,
  dots: true,
  slidesToShow: 2,
  slidesToScroll: 2,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2,
        centerMode: true,
      },
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        centerMode: true,
      },
    },
    {
      breakpoint: 425,
      settings: {
        slidesToShow: 1.2,
        slidesToScroll: 1,
        centerMode: false,
        infinite: false,
      },
    },
  ],
};

export const values = [
  {
    id: 1,
    heading: 'Collaborate <br /> with compassion',
    img: '../img/life-at-gojek/values/collaborate-with-compassion.svg',
    alt: 'Collaborate with compassion',
    content: [
      'Be a pleasure to work with',
      'Support others in areas beyond your scope',
      'Consider how your actions affect others',
    ],
  },
  {
    id: 2,
    heading: 'Criticism <br /> is a gift',
    img: '../img/life-at-gojek/values/criticism is-a-gift.svg',
    alt: 'Criticism is a gift',
    content: [
      'Actively seek feedback',
      'Proactively give helpful feedback',
      'Genuinely act upon feedback given',
    ],
  },
  {
    id: 3,
    heading: 'Be fast <br /> and fearless',
    img: '../img/life-at-gojek/values/be-fast-and-fearless.svg',
    alt: 'Be fast and fearless',
    content: [
      'Take calculated risks',
      'Value failure as much as success',
      'Have a strong sense of urgency',
    ],
  },
  {
    id: 4,
    heading: 'Stand up for <br /> what you believe in',
    img: '../img/life-at-gojek/values/belief.svg',
    alt: 'Stand up for what you believe in',
    content: ['Say what you mean', 'Have the courage to disagree', 'Have a strong moral compass'],
  },
  {
    id: 5,
    heading: 'Earn <br /> your title',
    img: '../img/life-at-gojek/values/earn-your-title.svg',
    alt: 'Earn your title',
    content: ['Walk the talk', 'Get down in the trenches', 'Trust your team'],
  },
  {
    id: 6,
    heading: 'Become <br />a scientist',
    img: '../img/life-at-gojek/values/become-a-scientist.svg',
    alt: 'Become a scientist',
    content: [
      'Follow the numbers intensively',
      'Find solutions in unexpected places',
      'Learn independently and share knowledge',
    ],
  },
  {
    id: 7,
    heading: 'Always <br /> be prepared',
    img: '../img/life-at-gojek/values/always-be-prepared.svg',
    alt: 'Always be prepared',
    content: ['Do your homework', 'Plan out every scenario', 'Take actions to reduce risk'],
  },
  {
    id: 8,
    heading: 'It’s not <br /> about you',
    img: '../img/life-at-gojek/values/its-not-about-you.svg',
    alt: 'It’s not about you',
    content: [
      'Put the company before self',
      'Be obsessed about customer problems',
      'Have a purpose beyond personal success',
    ],
  },
  {
    id: 9,
    heading: 'Communicate <br /> with purpose',
    img: '../img/life-at-gojek/values/communicate-with-purpose.svg',
    alt: 'Communicate with purpose',
    content: [
      'State objectives in every interaction',
      'Align early and consistently',
      'Focus on what is actionable',
    ],
  },
  {
    id: 10,
    heading: 'hoot <br /> for greatness',
    img: '../img/life-at-gojek/values/shoot-for-greatness.svg',
    alt: 'Shoot for greatness',
    content: ['Go the extra mile', 'Think big', 'Love challenges'],
  },
];
