export const perks = [
  {
    id: 1,
    title: 'Your work, your time',
    description: "We don’t ask when/whether you're coming or going.",
    bgColor: '#93328e',
    img: '../img/life-at-gojek/perks/your-work-your-time.svg',
    height: '430px',
    show: '1',
  },
  {
    id: 4,
    title: 'We help you stay connected',
    description: 'Mobile and internet bill reimbursement.',
    bgColor: '#fcaa00',
    height: '280px',
    show: '1',
  },
  {
    id: 7,
    title: 'Refer & earn',
    description: 'Meet friends for lunch, every other day.',
    bgColor: '#00aa13',
    img: '../img/life-at-gojek/perks/refer-and-earn.svg',
    height: '426px',
    show: '2',
  },
  {
    id: 10,
    title: 'The Gojek Cup',
    description: 'Our annual sports event is no child’s play.',
    bgColor: '#93328e',
    height: '280px',
    show: '2',
  },
  {
    id: 13,
    title: 'Health insurance',
    description: 'Life, surgery, dental, inpatient, outpatient and more.',
    bgColor: '#00aa13',
    height: '280px',
    show: '3',
  },
  {
    id: 16,
    title: '200-seater amphitheatre',
    description: 'For meetups, movies and madness.',
    bgColor: '#f4364c',
    height: '280px',
  },
  {
    id: 17,
    title: 'CSR Initiatives',
    description: 'Subsidising GoCar rides for the elderly with dementia + more.',
    bgColor: '#df1995',
    img: '../img/life-at-gojek/perks/csr-activities.svg',
    height: '426px',
    show: '3',
  },
  {
    id: 2,
    title: 'Fly for work & fun',
    description: 'Explore new offices, different cultures, and a thousand islands!',
    bgColor: '#ff7f32',
    height: '282px',
    show: '1',
  },
  {
    id: 5,
    title: 'Your health matters',
    description: 'Health and fitness related expenditure is on us',
    bgColor: '#f4364c',
    img: '../img/life-at-gojek/perks/health-benifits.svg',
    height: '426px',
    show: '1',
  },
  {
    id: 8,
    title: 'For moms-to-be',
    description: 'A 6-month maternity leave + WFH options. No questions asked.',
    bgColor: '#df1995',
    height: '280px',
    show: '2',
  },
  {
    id: 11,
    title: 'Corporate loans',
    description: 'Big goals? Allow us to lend a hand.',
    bgColor: '#00aed6',
    img: '../img/life-at-gojek/perks/corporate-loans.svg',
    height: '426px',
    show: '2',
  },
  {
    id: 14,
    title: 'Learning & development',
    description: 'Free courses on Coursera, and in-house mentorship.',
    bgColor: '#ff7f32',
    img: '../img/life-at-gojek/perks/learning-and-development.svg',
    height: '510px',
    show: '3',
  },
  {
    id: 18,
    title: 'Clubs for all',
    description: 'Football, Badminton, Boxing Yoga, Zumba, and more.',
    bgColor: '#00aa13',
    img: '../img/life-at-gojek/perks/clubs-for-all.svg',
    height: '514px',
    show: '3',
  },
  {
    id: 3,
    title: 'Voracious reader?',
    description: 'Let us pick up the tab for  books.',
    bgColor: '#00aa13',
    img: '../img/life-at-gojek/perks/voracious-reader.svg',
    height: '426px',
    show: '1',
  },
  {
    id: 6,
    title: 'We talk about mental health',
    description: 'Free counselling for employees & families.',
    bgColor: '#00aed6',
    height: '280px',
    show: '1',
  },
  {
    id: 12,
    title: 'Community learning',
    description: 'Industry-wide meetups, events and conferences. We pay. You learn.',
    bgColor: '#ff7f32',
    img: '../img/life-at-gojek/perks/community-learning.svg',
    height: '426px',
    show: '2',
  },
  {
    id: 9,
    title: 'Unity in diversity',
    description: 'Work with superstars from across 31 nationalities.',
    bgColor: '#f4364c',
    height: '280px',
    show: '2',
  },
  {
    id: 15,
    title: 'GoPay credits',
    description: 'Coz our growth is credited to you.',
    bgColor: '#00aed6',
    img: '../img/life-at-gojek/perks/gopay-credits.svg',
    height: '426px',
    show: '3',
  },
  {
    id: 19,
    title: 'Gamers’ got a life',
    description: 'We’ve got you playrooms with arcade games.',
    bgColor: '#93328e',
    height: '280px',
    show: '3',
  },
  {
    id: 20,
    title: 'Sleeping room',
    description: 'When in doubt, take a nap. Late hours? Stay over.',
    bgColor: '#f06400',
    height: '280px',
    show: '3',
  },
];

export const posts = [
  {
    id: 1,
    title: 'How GOJEK Manages 1 million Drivers With 12 Engineers',
    img: '../img/life-at-gojek/blog/managing-1-million-drivers.png',
    link: '#',
  },
  {
    id: 2,
    title: 'Why We Swear by the RCA',
    img: '../img/life-at-gojek/blog/why-we-swear-by-rca.png',
    link: '#',
  },
  {
    id: 3,
    title: 'How Design Can Build or Break a Business',
    img: '../img/life-at-gojek/blog/design-can-build-or-break-business.png',
    link: '#',
  },
  {
    id: 4,
    title: 'The Rise and Fall of Mod Apps',
    img: '../img/life-at-gojek/blog/rise-and-fall-of-mod-apps.png',
    link: '#',
  },
  {
    id: 5,
    title: 'When Canned Messages Opened a Can of Worms',
    img: '../img/life-at-gojek/blog/canned-messages.png',
    link: '#',
  },
  {
    id: 6,
    title: 'Don’t be Proud of being a Perfectionist',
    img: '../img/life-at-gojek/blog/dont-be-proud-of-perfectionist.png',
    link: '#',
  },
];

export const socialImpact = {
  heading: 'Social Impact',
  description:
    'Gojek is a verb in Southeast Asia. We got here because of our commitment to improve the lives of millions of Southeast Asians. A glimpse of how we’ve impacted the communities around us:',
  data: [
    {
      id: 4,
      title: 'The Rise and Fall of Mod Apps',
      image: '../img/life-at-gojek/social-impact.png',
      color: '#74D2E7',
    },
    {
      id: 3,
      title: 'How Design Can Build or Break a Business',
      image: '../img/life-at-gojek/social-impact.png',
      color: '#FDD086',
    },
    {
      id: 2,
      title: 'Gojek contributed a total of $7.1 billion to Indonesia’s economy in 2019.',
      image: '../img/life-at-gojek/social-impact.png',
      color: '#E2ACD7',
    },
    {
      id: 1,
      title: 'Gojek contributed a total of $7.1 billion to Indonesia’s economy in 2019.',
      image: '../img/life-at-gojek/social-impact.png',
      color: '#7CCC6C',
    },
  ],
};

export const teams = [
  {
    name: 'Kernel',
    slug: 'kernel',
    bgColor: '#ff695b',
    bgImg: '/img/careers/kernel.png',
  },
  {
    name: 'The Identity & Communication Platform',
    slug: 'identity-and-communication-platform',
    bgColor: '#ffb31c',
    bgImg: '/img/careers/identity-and-communication.png',
  },
  {
    name: 'Operations Platform',
    slug: 'operations-platform',
    bgColor: '#772583',
    bgImg: '/img/careers/operations.png',
  },
  {
    name: 'Kernel',
    slug: 'kernel',
    bgColor: '#ff695b',
    bgImg: '/img/careers/kernel.png',
  },
  {
    name: 'Test',
    slug: 'identity-and-communication-platform',
    bgColor: '#ffb31c',
    bgImg: '/img/careers/identity-and-communication.png',
  },
];

export const temsSliderSettings = {
  infinite: true,
  dots: true,
  slidesToShow: 2,
  slidesToScroll: 2,
  centerMode: true,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2,
        centerMode: true,
      },
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        centerMode: true,
      },
    },
    {
      breakpoint: 425,
      settings: {
        slidesToShow: 1.2,
        slidesToScroll: 1,
        centerMode: false,
        infinite: false,
      },
    },
  ],
};
